[project]
name = "fullstack-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thierry", email = "legros.thl@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "nbformat>=5.11.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "plotly>=7.1.0",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
]

[project.scripts]
fullstack-ai = "fullstack-ai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "N", "W"]
