# Python fundamentals 🐍

## What you will learn in this course 🧐🧐

Python is the most used language in data work. Every data pipeline, every analytics tool, every AI system you will touch uses it. Learning Python well means learning a skill you will use every single day in your career.

By the end of this course, you will be able to:

- Store business data in variables using the right **data type** (the kind of value, like text or number).
- Use **string methods** (built-in text actions) to clean messy customer data.
- Convert data between types when reading values from an API (a service that sends data to your program).
- Compare values and use `if`, `elif`, and `else` to make decisions on each order.
- Organize groups of orders using **lists**, **dictionaries**, and **tuples**.
- Process thousands of orders at once with `for` and `while` loops.

<Note type="tip" title="A concrete example">

To show Python fundamentals, we will build a simple program that processes coffee order data. Each concept works in many other situations. But tying them to one concrete example makes them easier to understand and remember.

</Note>

## Variables

The most basic instruction in any program is storing a piece of data. A **variable** is a name that points to a value in your computer's memory. 

You create a variable with a single `=` sign. The name goes on the left. The value goes on the right.

The next code block stores **seven pieces of data** about one coffee order from BeanStream. Each line stores one fact about the order. This is how every program starts: you name the things you care about, then you work with them later.

In [2]:
# Store data about one BeanStream order.
# Lines that start with "#" are comments. Python ignores them.
# Comments explain what the code does for human readers.

drink_name = "Oat Milk Caramel Latte"
customer = "Marco Polo"
store = "Berlin Central"
order_year = 2024
cups_sold = 142
shots = 2
loyalty_member = True

Seven cups now hold information about one coffee order. Python stored each value in memory and attached the label you chose.

`drink_name` holds the text of the drink. `order_year` holds the number 2024. `loyalty_member` holds the value `True`, which means this customer has a loyalty card.

Use the `print()` function to show a variable's contents. `print()` is a **function** (a named action). You write the name, open parentheses, put something inside, and close parentheses. Python then performs the action. The next code block prints three of our variables.

In [3]:
print(drink_name)
print(cups_sold)
print(loyalty_member)

Oat Milk Caramel Latte
142
True


In [11]:
test = True
if test:
    print("test = 0 c'est comme test = False")

type(test)

test = 0 c'est comme test = False


bool

`print(drink_name)` shows the text stored in `drink_name`. `print(cups_sold)` shows the number 142. `print(loyalty_member)` shows `True`. Each `print()` call makes one line of output.

### Data types

Not all values are the same kind. Python sorts values into different **data types**. The four you use most often:

- **String** (`str`) stores text. Anything between quotes is a string. Drink names, customer names, and order IDs are all strings.
- **Integer** (`int`) stores whole numbers with no decimal point. Cup counts, shot counts, and order years are integers.
- **Float** (`float`) stores decimal numbers. Drink prices, ratings, and ratios are floats.
- **Boolean** (`bool`) stores exactly `True` or `False`. Loyalty status and "is the drink hot" flags are booleans.

The `type()` function tells you which data type a variable holds. This is your first check when something goes wrong in a pipeline. The next code block checks the type of each of our variables.

In [12]:
print(type(drink_name))       # str
print(type(cups_sold))        # int
print(type(loyalty_member))   # bool

# Floats store decimal numbers
drink_price = 4.95
print(type(drink_price))      # float

<class 'str'>
<class 'int'>
<class 'bool'>
<class 'float'>


`type(drink_name)` returns `<class 'str'>` because the drink name is text. `type(cups_sold)` returns `<class 'int'>` because 142 is a whole number. `type(loyalty_member)` returns `<class 'bool'>` because `True` is a boolean. `type(drink_price)` returns `<class 'float'>` because 4.95 has a decimal point.

**Types matter because Python treats each type differently.** 

Python use automatic rules to decide what happens when you combine variables. If you add two integers, Python gives you their sum. If you add two strings, Python joins them together. But if you try to add a string and an integer, Python does not know what to do and gives you an error.

### f-strings

The professional way to format output in Python is the **f-string** (a string with variables inside it). Put an `f` before the opening quote. Then insert variables right inside curly braces `{}`. Python swaps each `{}` for the variable's value.

The next code block uses f-strings to make clean, readable output.

In [13]:
# f-strings put variables right inside text
print(f"Drink: {drink_name}")
print(f"Cups sold: {cups_sold}")

# Calculate cups per shot, then format the result
cups_per_shot = cups_sold / shots
print(f"Cups per shot: {cups_per_shot:.1f}")

Drink: Oat Milk Caramel Latte
Cups sold: 142
Cups per shot: 71.0


`f"Drink: {drink_name}"` inserts the value of `drink_name` into the string. The result is `Drink: Oat Milk Caramel Latte`.

`cups_sold / shots` divides 142 by 2. The result is 71.0. The `:.1f` inside the braces rounds the number to one decimal place. So the output shows `71.0`.

f-strings replace the old way of gluing strings together with `+`. Use them everywhere.

### String methods

Remember we said that Python treats each data type differently? Strings have built-in actions called **methods**. You call a method with a dot after the string variable. Methods return a *new* string. The original stays the same.

Here are the most useful string methods for cleaning data:

| Method | What it does |
|--------|--------------|   
| `lower()` | Converts all letters to lowercase |
| `upper()` | Converts all letters to uppercase |
| `title()` | Converts the first letter of each word to uppercase |
| `startswith(prefix)` | Returns `True` if the string starts with the specified `prefix` |  
| `endswith(suffix)` | Returns `True` if the string ends with the specified `suffix` |  
| `find(sub)` | Returns the lowest index where the substring `sub` is found|
| `count(sub)` | Returns the number of occurrences of the substring `sub` |
| `strip()` | Removes extra spaces from the start and end of the string |
| `replace(old, new)` | Replaces all occurrences of `old` with `new` |
| `split(sep)` | Splits the string into a list of parts using `sep` as the separator |
| `join(iterable)` | Joins the elements of `iterable` into a single string, separated by the string on which it is called |

Let's use these methods on the `category` variable. 

In [5]:
category = "Seasonal Specials"

# Each method returns a NEW string
upper_category = category.upper()
print(upper_category)                       # SEASONAL SPECIALS

lower_category = category.lower()
print(lower_category)                       # seasonal specials

title_category = category.title()
print(title_category)                       # Seasonal Specials

starts_with_sea = category.startswith("Sea")
print(starts_with_sea)                      # True

ends_with_als = category.endswith("als")
print(ends_with_als)                        # True

position_of_spec = category.find("Spec")
print(position_of_spec)                     # 9

count_of_s = category.count("s")
print(count_of_s)                           # 2

SEASONAL SPECIALS
seasonal specials
Seasonal Specials
True
True
9
2


`category.upper()` creates a new string where every letter is uppercase. The original `category` still holds `"Seasonal Specials"`. `category.find("Spec")` returns 9 because the letter `S` in `Spec` sits at position 9 (counting from 0). `category.count("s")` counts every lowercase `s` in the string and returns 2.

The next code blocks show `strip()`, `replace()`, `split()`, and `join()` in action. These four methods are the workhorses of data cleaning.

In [14]:
# strip() removes spaces at the start and end
messy_drink = "  Caramel Latte  "
clean_drink = messy_drink.strip()
print(f"'{messy_drink}' -> '{clean_drink}'")

'  Caramel Latte  ' -> 'Caramel Latte'


In [16]:
# replace() swaps one piece of text for another
new_drink = clean_drink.replace("Caramel", "Vanilla")
print(new_drink)                       # Vanilla Latte

Vanilla Latte


In [17]:
# split() breaks a string into a list of pieces
words = new_drink.split(" ")
print(words)                           # ['Vanilla', 'Latte']

['Vanilla', 'Latte']


In [18]:
# join() glues a list back into one string
joined = " - ".join(words)
print(joined)                          # Vanilla - Latte

Vanilla - Latte


`messy_drink.strip()` removes the extra spaces at the start and end. The result is a clean string with no spaces around it. `clean_drink.replace("Caramel", "Vanilla")` finds the word `"Caramel"` and swaps it for `"Vanilla"`. `new_drink.split(" ")` cuts the string at every space and returns a list of words. `" - ".join(words)` takes the list `["Vanilla", "Latte"]` and glues them together with `" - "` between each word.

These methods become key when your pipeline processes real data. Drink names arrive with extra spaces. Customer names use mixed capitalization. Order IDs come with prefixes you need to remove. You will use `strip()`, `replace()`, `split()`, and `join()` every single day.

### Type conversion

The BeanStream ordering [API](https://aws.amazon.com/what-is/api/#:~:text=API%20stands%20for%20Application%20Programming,of%20service%20between%20two%20applications.) returns everything as text, including numbers. A cups-sold count of `"142"` is a string. You cannot do math on it until you convert it. Python gives you `int()`, `float()`, `str()`, and `bool()` for conversion.

The next code block shows what happens when you convert a string to an integer.

In [19]:
# Data arrives from the API as text
cups_text = "142"
print(type(cups_text))   # str

# Convert to integer for math
cups_number = int(cups_text)
print(type(cups_number)) # int

# Math works now
result = cups_number + 10
print(result)            # 152

<class 'str'>
<class 'int'>
152


`cups_text` is a string. It looks like a number, but Python treats it as text. `int(cups_text)` reads the text `"142"` and creates the integer `142`. Now you can do math with it. `cups_number + 10` makes `152`.

## Comparisons and conditional execution

Now that you know how to store and change data, you need a way to make decisions based on that data. A **comparison** asks a question and returns a boolean: `True` or `False`. Python gives you six comparison operators.

| Operator | Meaning | Example | Result |
|----------|---------|---------|--------|
| `==` | Equal to | `5 == 5` | `True` |
| `!=` | Not equal to | `5 != 3` | `True` |
| `>` | Greater than | `5 > 3` | `True` |
| `<` | Less than | `5 < 3` | `False` |
| `>=` | Greater or equal | `5 >= 5` | `True` |
| `<=` | Less or equal | `3 <= 5` | `True` |

The next code block uses comparison operators and the logical keywords `and`, `or`, and `not` to check coffee order data.

In [11]:
cups_sold = 142
loyalty_member = True

print(cups_sold > 100)          # True
print(cups_sold == 200)         # False
print(loyalty_member != False)  # True

# Combine conditions with 'and', 'or', 'not'
top_loyalty_drink = cups_sold > 100 and loyalty_member
print(f"Top drink with loyal customer: {top_loyalty_drink}")

True
False
True
Top drink with loyal customer: True


`cups_sold > 100` asks "is 142 greater than 100?" The answer is `True`. `cups_sold == 200` asks "is 142 equal to 200?" The answer is `False`. `loyalty_member != False` asks "is True not equal to False?" The answer is `True`.

`cups_sold > 100 and loyalty_member` joins two conditions with `and`. Both must be True for the result to be True. Since 142 is greater than 100 *and* the customer is a loyalty member, the result is `True`.

Comparisons produce True or False. We can use that result to control which code runs. This is called **conditional execution**.

**Conditional statements** use that result to choose which code runs. `if` checks a condition. When True, Python runs the indented block. When False, Python skips it. `else` gives a fallback block. `elif` (short for "else if") adds more checks.

The next code block gives a drink a priority level based on how many cups were sold.

In [22]:
# Give a priority level based on cups sold
cups_sold = 142

if cups_sold >= 200:
    priority = "High"
else:
    priority = "Medium" # <- this instruction will be executed because 142 is not >= 200

print(f"Drink priority: {priority}")

Drink priority: Medium


`cups_sold >= 200` checks if 142 is greater than or equal to 200. It is not. So Python skips the `if` block and runs the `else` block instead. The variable `priority` gets the value `"Medium"`.

The first condition that is True decides which block runs. If no conditions are True, the `else` block runs. You can have as many `elif` blocks as you need. But only one `else` at the end.

Also, the first condition that matches runs. The rest are skipped. This means order matters. Put the most specific conditions first and the most general last. The next code block uses `elif` to make several priority levels at once.

In [23]:
cups_sold = 142

if cups_sold >= 200:
    priority = "critical"
elif cups_sold >= 100:
    priority = "high" # This instruction will be executed because 142 is >= 100 and the previous condition was False
elif cups_sold >= 50:
    priority = "medium"
else:
    priority = "low"

print(f"Priority: {priority}")

Priority: high


Python checks each condition from top to bottom. `142 >= 200` is False, so it moves on. `142 >= 100` is True, so `priority` becomes `"high"`. Python stops checking and skips the rest of the `elif` and `else` blocks.

## Logical Operators

Logical operators are used to combine multiple conditions into a single expression. The three main operators are `and`, `or`, and `not`.

| Operator | Meaning                               | Example          | Result  |
| -------- | ------------------------------------- | ---------------- | ------- |
| `and`    | All conditions must be `True`         | `True and False` | `False` |
| `or`     | At least one condition must be `True` | `True or False`  | `True`  |
| `not`    | Reverses the condition                | `not True`       | `False` |

The following example demonstrates a more realistic pipeline classification. It combines logical operators (`and`) with control flow statements (`if` / `elif` / `else`) to route drinks into different processing queues based on multiple conditions.


In [24]:
drink_name = "Oat Milk Caramel Latte"
cups_sold = 142
loyalty_member = True

if cups_sold >= 100 and loyalty_member:
    category = "popular" # This instruction will be executed because both conditions are True
else:
    category = "regular"

print(category)

popular


## Data structures

So far, every variable has held one single value. One drink name. One cup count. One loyalty flag. But real business data comes in groups. You have hundreds of drinks. Thousands of orders. Dozens of categories.

Python gives you strong **data structures** to organize and manage groups of related data. The three you will use most often are:

- **Lists**: ordered collections where you read items by position.
- **Dictionaries**: named collections where you read items by key.
- **Tuples**: fixed collections that cannot change after creation.

<Note type="tip" title="DataFrames">
*DataFrames* (big data tables) come in a later this training. For now, these three structures cover almost every need.
</Note>

### Lists

A **list** stores many items in order. You create it with square brackets `[]`. Lists can hold any type: strings, numbers, booleans, even other lists.

The next code block creates a list of drink categories and reads items by position.

In [25]:
categories = ["Espresso Drinks", "Cold Brew", "Seasonal Specials",
              "Tea Lattes", "Pastries"]

# Read items by position (index starts at 0)
first_category = categories[0]
print(first_category)          # First item

last_category = categories[-1]
print(last_category)           # Last item

middle_slice = categories[1:3]
print(middle_slice)            # Slice: items at index 1 and 2

total_categories = len(categories)
print(total_categories)        # Number of items: 5

Espresso Drinks
Pastries
['Cold Brew', 'Seasonal Specials']
5


<img src ="https://ai-essentials-assets.s3.eu-west-3.amazonaws.com/M01-Python_for_AI/AIE-M01-D01-Slicing.png"/>

`categories[0]` returns the first item. Python counts from 0, not 1. `categories[-1]` returns the last item. Negative indexes count from the end. `categories[1:3]` returns a **slice** (a chunk of the list): items at positions 1 and 2. Note that the end index is not included. `len(categories)` returns the number of items in the list.

Lists are **mutable** (you can change them after you create them). You can **add**, **remove**, and **change** items. The next code block shows common list operations.

In [26]:
# Build a processing queue by adding items one at a time
queue = []
queue.append("ORD-001")

In [27]:
queue.append("ORD-002")
queue.append("ORD-003")
print(f"Queue: {queue}")

Queue: ['ORD-001', 'ORD-002', 'ORD-003']


In [18]:
# Remove one specific item
queue.remove("ORD-002")
print(f"After remove: {queue}")

After remove: ['ORD-001', 'ORD-003']


In [28]:
# Sort and aggregate
counts = [142, 89, 201, 67, 312]
counts.sort(reverse=True)
print(f"Sorted: {counts}")

Sorted: [312, 201, 142, 89, 67]


In [29]:
# Calculate max, min, and average
max_count = max(counts)
min_count = min(counts)
total = sum(counts)
average = total / len(counts)
print(f"Max: {max_count}, Min: {min_count}, Avg: {average:.1f}")

Max: 312, Min: 67, Avg: 162.2


`queue.append("ORD-001")` adds one item to the end of the list. `queue.remove("ORD-002")` finds and removes the first match of that value. `counts.sort(reverse=True)` sorts the list from largest to smallest. *This changes the list itself.* `max()`, `min()`, and `sum()` are built-in functions that work on any list of numbers. `len(counts)` returns the number of items. Dividing `total` by `len(counts)` gives the average.

### Dictionaries

A **dictionary** stores data as **key-value pairs**. Instead of reading items by position, you read them by name. Think of it as a real dictionary. You look up a word (the key) to find its meaning (the value).

Create a dictionary with curly braces `{}` using the pattern `key: value`. The next code block stores all the data for one order in a single dictionary.

In [31]:
# One order as a dictionary. All data in one place.
order = {
    "order_id": "ORD-001",
    "drink": "Oat Milk Caramel Latte",
    "customer": "Zhang Wei",
    "category": "Seasonal Specials",
    "cups_sold": 142,
    "shots": 2,
    "loyalty_member": True
}

print(order["drink"])
print(order["cups_sold"])

Oat Milk Caramel Latte
142


Compare this to storing the same data in separate variables. All fields for one order now live in a single structure. You read them by name, not by remembering variable names spread across many lines. `order["cups_sold"]` explains itself. Anyone reading this code knows what it means.

These three dictionary methods are essential for working with nested data:
- `.items()`: returns a list of key-value pairs as tuples. You can loop through these pairs to access both keys and values at the same time.
- `.keys()`: returns a list of all the keys in the dictionary. You can loop through these keys to access their corresponding values.
- `.values()`: returns a list of all the values in the dictionary. You can loop through these values if you only care about them and not the keys.

In [32]:
list(order.items())

[('order_id', 'ORD-001'),
 ('drink', 'Oat Milk Caramel Latte'),
 ('customer', 'Zhang Wei'),
 ('category', 'Seasonal Specials'),
 ('cups_sold', 142),
 ('shots', 2),
 ('loyalty_member', True)]

In [33]:
list(order.keys())

['order_id',
 'drink',
 'customer',
 'category',
 'cups_sold',
 'shots',
 'loyalty_member']

In [34]:
list(order.values())

['ORD-001',
 'Oat Milk Caramel Latte',
 'Zhang Wei',
 'Seasonal Specials',
 142,
 2,
 True]

#### Modifying dictionaries

Dictionaries are mutable. You can add new keys, update existing values, and safely read keys that might not exist. The next code block shows all three.

In [36]:
# Add a new field
order["popularity_level"] = "high"
print(f"Popularity: {order['popularity_level']}")


Popularity: high


In [37]:
# Update an existing value
order["cups_sold"] = 157
print(f"Updated cups sold: {order['cups_sold']}")

Updated cups sold: 157


In [38]:
# Safe access with .get(). Returns default if key is missing.
notes = order.get("notes", "No notes available")
print(f"Notes: {notes}")

Notes: No notes available


`order["popularity_level"] = "high"` adds a brand new key to the dictionary. `order["cups_sold"] = 157` overwrites the old value (142) with the new one (157). `order.get("notes", "No notes available")` tries to find the key `"notes"`. Since it does not exist, it returns the default value instead of crashing.

<Note type="important" title="Always use .get() for external data">

Reading a missing key with `order["notes"]` crashes your program with a `KeyError`. The `.get()` method returns a default value instead. Use `.get()` when you process data from APIs or files. Fields that were there yesterday might be missing today.

</Note>

### Lists of dictionaries

The most common pattern in data engineering is a **list of dictionaries**. Each dictionary is one record. The list holds all records. This is exactly how the BeanStream ordering API returns search results. It is also how **JSON** files, **CSV**-loaded rows, and **database** queries look in Python.

The next code block creates a list of order dictionaries. Each dictionary is one coffee order. The list holds five orders in total.

In [39]:
orders = [
    {"order_id": "ORD-001", "drink": "Oat Milk Caramel Latte",
     "cups_sold": 142, "loyalty_member": True},
    {"order_id": "ORD-002", "drink": "Iced Vanilla Matcha",
     "cups_sold": 89, "loyalty_member": False},
    {"order_id": "ORD-003", "drink": "Pumpkin Spice Latte",
     "cups_sold": 201, "loyalty_member": True},
    {"order_id": "ORD-004", "drink": "Classic Espresso",
     "cups_sold": 67, "loyalty_member": False},
    {"order_id": "ORD-010", "drink": "Cold Brew Float",
     "cups_sold": 312, "loyalty_member": True}
]

# Read the first order
first_order = orders[0]
print(first_order)

{'order_id': 'ORD-001', 'drink': 'Oat Milk Caramel Latte', 'cups_sold': 142, 'loyalty_member': True}


In [29]:
# Read a specific field of the first order
first_drink = first_order["drink"]
print(first_drink)

Oat Milk Caramel Latte


`orders[0]` returns the first dictionary in the list. `first_order["drink"]` reads the `"drink"` field of that dictionary. You mix list-style access (by position) with dictionary-style access (by key). This is the main shape of real business data in Python.

To access all orders, you will soon use loops. But for now, you can read them one at a time to understand the structure. Each order is self-contained. No more parallel lists. No more index tracking. Every field for one order lives in one place. This is the structure you will soon process with loops.

### Tuples

A **tuple** looks like a list but uses parentheses. The key difference: tuples are **immutable** (they cannot change). Once you create them, you cannot add, remove, or change items. Use tuples for data that must stay fixed. Configuration values, API endpoints, and fixed records are good examples.

The next code block creates a tuple for the BeanStream API configuration and shows what happens when you try to change it.

In [40]:
# Fixed API configuration. Should never change while the program runs.
api_config = ("https://api.beanstream.com/orders/v2", "json", 25)

# Unpack into separate variables
endpoint, format_type, page_size = api_config
print(f"Endpoint: {endpoint}")
print(f"Page size: {page_size}")

# Trying to change it raises an error
# We will see how to handle errors in a future lesson. For now, just catch the error and print it.
try: 
    api_config[2] = 50
except TypeError as e:
    print(f"Error: {e}")

Endpoint: https://api.beanstream.com/orders/v2
Page size: 25
Error: 'tuple' object does not support item assignment


`api_config` is a tuple with three items. `endpoint, format_type, page_size = api_config` **unpacks** the tuple. It assigns each item to a separate variable in one line. This only works if the number of variables matches the number of items.

`api_config[2] = 50` tries to change the third item. Python raises a `TypeError` because tuples do not allow changes. This is the whole point of tuples: they protect data from accidental changes.

## Loops

You now know how to store groups of data in lists and dictionaries. The next question is: how do you do the same thing to every item in a group? For one drink, you write one `if/else` block. For a thousand drinks, you need **loops**.

A loop repeats a block of code many times. Python has two loop types:

- `for` loops walk through every item in a collection (a list, a dictionary, a range of numbers).
- `while` loops repeat as long as a condition stays `True`.

The `for` loop is by far the most common in data work. You will use it every day.

### For loops on lists

A `for` loop takes a collection and runs the same code once for each item. The next code block loops through the list of drink categories we created earlier and prints each one.

In [41]:
# categories is a list of strings
categories = ["Espresso Drinks", "Cold Brew", "Seasonal Specials",
              "Tea Lattes", "Pastries"]

# Process each category one by one
for category in categories:
    print(f"Processing orders in: {category}")

Processing orders in: Espresso Drinks
Processing orders in: Cold Brew
Processing orders in: Seasonal Specials
Processing orders in: Tea Lattes
Processing orders in: Pastries


Python ran `print()` five times. Once per category. On each pass, the variable `category` held a different value from the list. First `"Espresso Drinks"`, then `"Cold Brew"`, and so on. The loop stops after the last item.

The real power comes when you mix loops with conditionals. The next code block labels each cups-sold count as `"HIGH"` or `"standard"`.

In [42]:
cups_counts = [142, 89, 201, 67, 53, 178, 34, 312]

for count in cups_counts:
    if count >= 100:
        level = "HIGH"
    else:
        level = "standard"
    print(f"  Cups sold: {count} -> {level}")

  Cups sold: 142 -> HIGH
  Cups sold: 89 -> standard
  Cups sold: 201 -> HIGH
  Cups sold: 67 -> standard
  Cups sold: 53 -> standard
  Cups sold: 178 -> HIGH
  Cups sold: 34 -> standard
  Cups sold: 312 -> HIGH


For each number in `cups_counts`, the loop checks if it is 100 or more. If yes, `level` becomes `"HIGH"`. If no, `level` becomes `"standard"`. The `{count:>4}` in the f-string pushes the number to the right in a space 4 characters wide. This makes the output line up neatly.

### Building new lists with loops

A very common task is making a new list from an existing one. You loop through the original, apply a rule, and collect the results. This is one of the most important patterns in all of data work.

The next code block uses the `orders` list of dictionaries from earlier. It pulls all cups-sold counts into a new list.

In [43]:
orders = [
    {"order_id": "ORD-001", "drink": "Oat Milk Caramel Latte",
     "cups_sold": 142, "loyalty_member": True},
    {"order_id": "ORD-002", "drink": "Iced Vanilla Matcha",
     "cups_sold": 89, "loyalty_member": False},
    {"order_id": "ORD-003", "drink": "Pumpkin Spice Latte",
     "cups_sold": 201, "loyalty_member": True},
    {"order_id": "ORD-004", "drink": "Classic Espresso",
     "cups_sold": 67, "loyalty_member": False},
    {"order_id": "ORD-010", "drink": "Cold Brew Float",
     "cups_sold": 312, "loyalty_member": True}
]

# Pull all cups-sold counts into a new list
all_cups = []
for order in orders:
    count = order["cups_sold"]
    all_cups.append(count)

print(f"All cups sold: {all_cups}")

All cups sold: [142, 89, 201, 67, 312]


The loop starts with an empty list `all_cups`. For each order in the list, it reads the `"cups_sold"` value and appends it. After five passes, the new list holds `[142, 89, 201, 67, 312]`. You now have one list you can sum, sort, or feed to another function.

The next code block adds a filter. It only collects drinks bought by loyalty members.

In [34]:
# Filter: only drinks bought by loyalty members
loyalty_drinks = []
for order in orders:
    if order["loyalty_member"]:
        drink = order["drink"]
        loyalty_drinks.append(drink)

print(f"Loyalty drinks: {loyalty_drinks}")

Loyalty drinks: ['Oat Milk Caramel Latte', 'Pumpkin Spice Latte', 'Cold Brew Float']


This loop adds an `if` check before the `append`. It only appends drinks where `order["loyalty_member"]` is `True`. Three of the five orders are from loyalty members, so the result list has three drinks. 

This pattern of **"start empty, loop, conditionally append"** appears in almost every data pipeline you will ever write. Filter orders by city. Filter products by category. Filter users by signup date. The shape is always the same.

### range() and enumerate()

Sometimes you do not have a list yet. You want to repeat something a fixed number of times. Or you want to know the position of each item as you loop. Python gives you two helpers for this.

`range()` makes a sequence of numbers. `range(5)` produces 0, 1, 2, 3, 4. `range(0, 50, 10)` produces 0, 10, 20, 30, 40. The third number is the **step size** (how much to add each time).

`enumerate()` pairs each item with its position. This is useful for numbering and error tracking.

The next code block mimics fetching orders from the API in batches of 10.

In [44]:
# Mimic fetching orders in batches from the API
for start in range(0, 50, 10):
    first_order = start + 1
    last_order = start + 10
    print(f"Fetching orders {first_order} to {last_order}...")

Fetching orders 1 to 10...
Fetching orders 11 to 20...
Fetching orders 21 to 30...
Fetching orders 31 to 40...
Fetching orders 41 to 50...


In [45]:
# enumerate() gives you position + value
categories = ["Espresso Drinks", "Cold Brew", "Seasonal Specials"]

for index, category in enumerate(categories):
    print(f"  [{index}] {category}")

  [0] Espresso Drinks
  [1] Cold Brew
  [2] Seasonal Specials


`range(0, 50, 10)` makes the numbers 0, 10, 20, 30, 40. The loop runs five times. Each time, `start` holds the next number. The code adds 1 and 10 to work out the human-readable batch range.

`enumerate(categories)` pairs each category with its position. On the first pass, `index` is 0 and `category` is `"Espresso Drinks"`. On the second pass, `index` is 1 and `category` is `"Cold Brew"`. This is cleaner than tracking a separate counter variable.

### For loops on nested data
Let's say you have a list of dictionaries (like the `orders` list). You want to loop through each order and read a specific field. This is a common pattern when processing API data, JSON files, or database query results.

You need to loop through the list of orders. For each order (which is a dictionary), you read the field you want. This is called **nested data** because you have one structure (a list) that contains another structure (dictionaries).

In [46]:
orders = [
    {"order_id": "ORD-001", "drink": "Oat Milk Caramel Latte",
     "cups_sold": 142, "loyalty_member": True},
    {"order_id": "ORD-002", "drink": "Iced Vanilla Matcha",
     "cups_sold": 89, "loyalty_member": False},
    {"order_id": "ORD-003", "drink": "Pumpkin Spice Latte",
     "cups_sold": 201, "loyalty_member": True},
    {"order_id": "ORD-004", "drink": "Classic Espresso",
     "cups_sold": 67, "loyalty_member": False},
    {"order_id": "ORD-010", "drink": "Cold Brew Float",
     "cups_sold": 312, "loyalty_member": True}
]

for order in orders:
    for key, value in order.items():
        print(f"{key}: {value}")
    print()  # Add a blank line between orders


order_id: ORD-001
drink: Oat Milk Caramel Latte
cups_sold: 142
loyalty_member: True

order_id: ORD-002
drink: Iced Vanilla Matcha
cups_sold: 89
loyalty_member: False

order_id: ORD-003
drink: Pumpkin Spice Latte
cups_sold: 201
loyalty_member: True

order_id: ORD-004
drink: Classic Espresso
cups_sold: 67
loyalty_member: False

order_id: ORD-010
drink: Cold Brew Float
cups_sold: 312
loyalty_member: True



### While loops

A `while` loop **keeps going as long as a condition stays True**. Use it when you do not know ahead of time how many times you need to repeat. A common example is paging through API results until no more pages are left.

The next code block mimics fetching pages from the BeanStream API.

In [47]:
current_page = 1
total_pages = 5

while current_page <= total_pages:
    print(f"Fetching page {current_page} of {total_pages}...")
    current_page += 1  # Without this line, the loop runs forever

print("All pages retrieved.")

Fetching page 1 of 5...
Fetching page 2 of 5...
Fetching page 3 of 5...
Fetching page 4 of 5...
Fetching page 5 of 5...
All pages retrieved.


The loop starts with `current_page = 1`. Each time, it prints the current page and then adds 1 with `current_page += 1`. When `current_page` reaches 6, the condition `6 <= 5` is False. The loop stops. Python then runs the line after the loop.

<Note type="important" title="Avoid infinite loops">

A `while` loop runs forever if its condition never becomes False. Always make sure something inside the loop changes the condition. Forgetting `current_page += 1` above creates an **infinite loop**. If this happens, click the stop button in the toolbar.

</Note>

`break` exits the loop right away. `continue` skips the current item and moves to the next. The next two code blocks show each one.

In [48]:
# break: stop on the first critical error
orders_status = ["valid", "valid", "CANCELLED", "valid"]

for status in orders_status:
    if status == "CANCELLED":
        print("Cancelled order found. Stopping.")
        break
    print(f"Processing: {status}")

Processing: valid
Processing: valid
Cancelled order found. Stopping.


In [40]:
# continue: skip bad items without stopping
cups_counts = [142, 0, 89, 0, 201, 67]

for count in cups_counts:
    if count == 0:
        continue  # Skip zero-cup orders
    print(f"Processing order with {count} cups")

Processing order with 142 cups
Processing order with 89 cups
Processing order with 201 cups
Processing order with 67 cups


In the first loop, `break` stops the whole loop as soon as a cancelled order shows up. The fourth item (`"valid"`) is never reached.

In the second loop, `continue` skips only the current item. When `count` is 0, Python jumps back to the top of the loop and moves to the next number. The loop still processes every non-zero item.

<Note type="tip" title="When to use for vs while">

Use `for` when you know how many times to repeat. For example, processing a list of orders. Use `while` when you repeat until a condition changes. For example, paging until no more pages are left.

</Note>

## Resources 📚📚

- [Official Python tutorial](https://docs.python.org/3/tutorial/)
- [Python data structures documentation](https://docs.python.org/3/tutorial/datastructures.html)
- [Variables](https://realpython.com/python-variables/) 
- [Dictionaries](https://realpython.com/python-dicts/) 